package constants

const (
	POSTGRES_HOST                = "POSTGRES_HOST"
	POSTGRES_PORT                = "POSTGRES_PORT"
	POSTGRES_USER                = "POSTGRES_USER"
	POSTGRES_PASS                = "POSTGRES_PASS"
	POSTGRES_DBNAME              = "POSTGRES_DBNAME"
	POSTGRES_MAX_IDLE_CONNS      = "POSTGRES_MAX_IDLE_CONNS"
	POSTGRES_MAX_OPEN_CONNS      = "POSTGRES_MAX_OPEN_CONNS"
	POSTGRES_MAX_LIFE_TIME_CONNS = "POSTGRES_MAX_LIFE_TIME_CONNS"
	POSTGRES_MAX_IDLE_TIME_CONNS = "POSTGRES_MAX_IDLE_TIME_CONNS"

	APP_PORT = "APP_PORT"
)
